platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: source-code

outputs:
  - name: build-output

caches:
  - path: source-code/.m2

run:
  path: source-code/ci/tasks/package.sh
